
import django.utils.timezone
from django.db import migrations, models
import accounts.models

import random
import string
from django.db import migrations, models
import accounts.models

# 랜덤 닉네임 생성 함수
def generate_random_nickname():
    return ''.join(random.choices(string.ascii_letters + string.digits, k=8))  # 랜덤 8자리 문자열

# 기존 사용자들에게 고유한 랜덤 닉네임을 할당하는 함수
def set_unique_nicknames(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    for user in User.objects.all():
        if not user.nickname:  # 만약 nickname이 비어 있으면
            user.nickname = generate_random_nickname()  # 고유한 랜덤 닉네임 할당
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),  # 이전 마이그레이션 파일
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[ 
                # UserManager 등 필요한 경우 추가
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Prefer not to say')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=accounts.models.generate_random_nickname, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
        # 기존 사용자들에 대해 랜덤 닉네임을 채우는 작업
        migrations.RunPython(set_unique_nicknames),
    ]

# =========================================================

# # Generated by Django 4.2.16 on 2024-11-19 01:54

# import accounts.models
# from django.db import migrations, models
# import django.utils.timezone


# class Migration(migrations.Migration):

#     dependencies = [
#         ('accounts', '0001_initial'),
#     ]

#     operations = [
#         migrations.AlterModelOptions(
#             name='user',
#             options={},
#         ),
#         migrations.AlterModelManagers(
#             name='user',
#             managers=[
#             ],
#         ),
#         migrations.RemoveField(
#             model_name='user',
#             name='date_joined',
#         ),
#         migrations.RemoveField(
#             model_name='user',
#             name='email',
#         ),
#         migrations.RemoveField(
#             model_name='user',
#             name='first_name',
#         ),
#         migrations.RemoveField(
#             model_name='user',
#             name='last_name',
#         ),
#         migrations.AddField(
#             model_name='user',
#             name='age',
#             field=models.PositiveIntegerField(default=20),
#         ),
#         migrations.AddField(
#             model_name='user',
#             name='created_at',
#             field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
#             preserve_default=False,
#         ),
#         migrations.AddField(
#             model_name='user',
#             name='gender',
#             field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Prefer not to say')], default='N', max_length=1),
#         ),
#         migrations.AddField(
#             model_name='user',
#             name='nickname',
#             field=models.CharField(default=accounts.models.generate_random_nickname, max_length=20, unique=True),
#         ),
#         migrations.AddField(
#             model_name='user',
#             name='profile_image',
#             field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_directory_path),
#         ),
#         migrations.AlterField(
#             model_name='user',
#             name='is_active',
#             field=models.BooleanField(default=True),
#         ),
#         migrations.AlterField(
#             model_name='user',
#             name='is_staff',
#             field=models.BooleanField(default=False),
#         ),
#         migrations.AlterField(
#             model_name='user',
#             name='username',
#             field=models.CharField(max_length=200, unique=True),
#         ),
#     ]

# =========================================================