# Generated by Django 4.2.16 on 2024-11-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('poster_path', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('tagline', models.TextField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('vote_avg', models.FloatField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('adult', models.BooleanField(blank=True, null=True)),
                ('movie_homepage', models.CharField(blank=True, max_length=255, null=True)),
                ('backdrop_image', models.CharField(blank=True, max_length=255, null=True)),
                ('production_com', models.CharField(blank=True, max_length=255, null=True)),
                ('original_lang', models.CharField(blank=True, max_length=20, null=True)),
                ('genre', models.TextField(blank=True, null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
                ('spoken_lang', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
