# Generated by Django 4.2.16 on 2024-11-22 03:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_like',
        ),
        migrations.AddField(
            model_name='review',
            name='like_reviews',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
