# Generated by Django 4.2.16 on 2024-11-25 08:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0006_alter_movie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='like_reviews',
            field=models.ManyToManyField(blank=True, related_name='like_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
