# Generated by Django 4.2.16 on 2024-11-22 04:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_remove_review_is_like_review_like_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='bookmark',
            field=models.ManyToManyField(blank=True, null=True, related_name='bookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='like_movies',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
